FROM nginx:1.22.1
COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY /etc/nginx/html/index.html /etc/nginx/html/index.html
COPY /etc/nginx/html/robots.txt /etc/nginx/html/robots.txt
COPY /etc/nginx/html/favicon.ico /etc/nginx/html/favicon.ico
COPY /etc/nginx/html/favicon.png /etc/nginx/html/favicon.png
COPY /etc/nginx/html/logo192.png /etc/nginx/html/logo192.png
COPY /etc/nginx/html/logo512.png /etc/nginx/html/logo512.png
COPY /etc/nginx/html/manifest.json /etc/nginx/html/manifest.json